### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81

### ISSUE THREAD

**Issue by rajif-id** [yzygitzh/Humanoid#11]
Hello,

I am using Python 3.6.7, tensorflow 1.12.0 on Windows 10.
Humanoid was installed successfully on my machine.

But, I found problem when try to running the command  "python agent.py -c config.json"
I got the following response:

```
D:\Lab\AIG-Ref\Humanoid-master>python agent.py -c config.json
C:\Users\Rajif\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Rajif\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Rajif\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Rajif\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\Rajif\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\Rajif\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Serving at localhost:50405
Traceback (most recent call last):
  File "agent.py", line 392, in <module>
    main()
  File "agent.py", line 388, in main
    run(opts.config_path)
  File "agent.py", line 376, in run
    agent = HumanoidAgent(config_json)
  File "agent.py", line 234, in __init__
    self.text_generator = TextGenerator(config_json)
  File "agent.py", line 36, in __init__
    self.embedding = json.load(f)
  File "C:\Users\Rajif\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 296, in load
    return loads(fp.read(),
  File "C:\Users\Rajif\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 25926717: character maps to <undefined>
```

Is there any suggestion to fix this problem?

**Comment by yzygitzh** [comment]
My gut feeling is the codec issue in Python json package. Maybe you can try this in WSL.

**Comment by rajif-id** [comment]
Hallo,

Thank you for answering.

However, I can fix this problem by adding value **encoding="utf8"** to to every parameter on **open()** function on file **agent.py**
For example **open(rico_config_path, "r")** --> modify --> **open(rico_config_path, "r", encoding="utf8")**

Regards.
