### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by tailup** [yzygitzh/Humanoid#4]
I am getting the following error When I run train.py.
What is the right way of doing this ?
```
root@c7e0a06df25a:~/data/github/Humanoid/train# python train.py -c config.json 
2019-12-01 03:27:23.654511: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-12-01 03:27:27,901 epoch: 0
image-name ['0.0' '0.0' '0.0'
 '/root/data/github/Humanoid/dataset/traces/filtered_traces/com.mobymax.mmdroid/trace_0/view_hierarchies/414.json']
image-data_type <class 'numpy.ndarray'>
self.frame_num 4
self.frame_num_type <class 'int'>
self.predicting_dim 1
self.predicting_dim_type <class 'int'>
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/root/data/github/Humanoid/train/loader.py", line 172, in next_batch_producer
    self.load_pickles(paths_to_load)
  File "/root/data/github/Humanoid/train/loader.py", line 133, in load_pickles
    image[self.frame_num - 1, :, :, -self.predicting_dim:] = 0.0
IndexError: too many indices for array
```
Thanks for the help.

**Comment by wangcong02345** [comment]
just uncomment prepare_data_humanoid.py L57:   filtered_data.append([sum_image_data, interact_data])
because the default script is just for validation not for train.

```
(base) cong@ubuntu:/data/src/Humanoid/rico$ git diff prepare_data_humanoid.py
diff --git a/rico/prepare_data_humanoid.py b/rico/prepare_data_humanoid.py
old mode 100644
new mode 100755
index 85722ca..c33930a
--- a/rico/prepare_data_humanoid.py
+++ b/rico/prepare_data_humanoid.py
@@ -54,10 +54,9 @@ def process_trace(trace_path, config_json):
             # print("Path:", view_tree_paths[i])
             # visualize_data(sum_image_data, config_json)
 
-            # filtered_data.append([sum_image_data, interact_data])
+            filtered_data.append([sum_image_data, interact_data])
             # for validation
-            filtered_data.append([view_tree_paths[i], interact_data,
-                                  np.unravel_index(np.argmax(heatmap_data[:,:,-1]), heatmap_data[:,:,-1].shape)])
+            # filtered_data.append([view_tree_paths[i], interact_data, np.unravel_index(np.argmax(heatmap_data[:,:,-1]), heatmap_data[:,:,-1].shape)])
 
     return filtered_data
```

**Comment by tailup** [comment]
I was able to solve it with your advice. Thank you.
